name: go-builder-plate

on:
    push:
        branches: master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.22

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and Push to GHCR
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/go-builder-plate:latest
        
            